services:
  db_lib:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    networks:
      - net

  app:
    build:
      dockerfile: ./Dockerfile
    command: [ "docker/app.sh" ]
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db_lib
    networks:
      - net

  nginx_lib:
    container_name: lib-nginx
    build: ./nginx
    volumes:
      - log_nginx:/var/log/nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - app
    networks:
      - net

volumes:
  postgres_volume:
  log_nginx:

networks:
  net:
    driver: bridge