services:
  db_lib:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    networks:
      - net

  app:
    build:
      dockerfile: ./Dockerfile
    command: ["docker/app.sh"]
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db_lib
    networks:
      - net

volumes:
  postgres_volume:

networks:
  net:
    driver: bridge