"""create table ReceivingBooks

Revision ID: 158d42af6d6d
Revises: e756558cd218
Create Date: 2025-05-18 19:10:00.673502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "158d42af6d6d"
down_revision: Union[str, None] = "e756558cd218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receivingbooks",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("reader_id", sa.Integer(), nullable=False),
        sa.Column("borrow_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("return_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reader_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reader_id", "book_id", name="idx_unique_reader_book"),
    )
    op.create_index(op.f("ix_receivingbooks_id"), "receivingbooks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receivingbooks_id"), table_name="receivingbooks")
    op.drop_table("receivingbooks")
    # ### end Alembic commands ###
