"""edit table books (update description)

Revision ID: e7877d560940
Revises: 6e86df0dec95
Create Date: 2025-05-20 09:02:51.564761

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import orm
from sqlalchemy import update

from src.models.book import Book

# revision identifiers, used by Alembic.
revision: str = "e7877d560940"
down_revision: Union[str, None] = "6e86df0dec95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    stmt = (update(Book).where(Book.description.is_(None)).values(description="Новое поступление"))
    session.execute(stmt)
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
