"""add books

Revision ID: 0ce3b5eb7b78
Revises: 6e86df0dec95
Create Date: 2025-05-19 10:57:58.434407

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import orm

from src.models.book import Book

# revision identifiers, used by Alembic.
revision: str = "0ce3b5eb7b78"
down_revision: Union[str, None] = "6e86df0dec95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    book1: Book = Book(
        title="Гарри Поттер и философский камень",
        author="Джоан Кэтлин Роулинг",
        release_date=2021,
        isbn="978-5-389-07435-4",
        count=1,
    )

    book2: Book = Book(
        title="Тайна мертвого ректора",
        author="Виктор Дашкевич",
        release_date=2025,
        isbn="978-5-04-204880-7",
        count=3,
    )

    book3: Book = Book(
        title="Бюро бракованных решений",
        author="Максим Суворов",
        release_date=2025,
        isbn="978-5-6053025-4-4",
        count=5,
    )

    book4: Book = Book(
        title="Капитанская дочка",
        author="Александр Пушкин",
        release_date=2019,
        isbn="978-5-17-092807-1",
        count=7,
    )

    book5: Book = Book(
        title="Анна Каренина",
        author="Лев Толстой",
        release_date=2024,
        isbn="978-5-17-087888-8",
        count=2,
    )

    session.add_all([book1, book2, book3, book4, book5])
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
