"""create users

Revision ID: eee11af4558c
Revises: e8bc0666bfb9
Create Date: 2025-05-18 13:50:12.582871

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import orm
import bcrypt

from src.models.user import User

# revision identifiers, used by Alembic.
revision: str = "eee11af4558c"
down_revision: Union[str, None] = "e8bc0666bfb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_hash_password(password: str) -> bytes:
    """
    Создание хеш пароля
    :param password: пароль
    :type password: str
    :rtype: bytes
    :return: хеш значение пароля
    """
    salt = bcrypt.gensalt()
    pwd_bytes: bytes = password.encode()
    return bcrypt.hashpw(pwd_bytes, salt)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    password_for_user1: str = create_hash_password("1qaz!QAZ").decode()
    user1: User = User(
        username="Admin1",
        email="admin1@lib.ru",
        hashed_password=password_for_user1,
        is_superuser=True,
    )
    password_for_user2: str = create_hash_password("2wsx@WSX").decode()
    user2: User = User(
        username="Admin2",
        email="admin2@lib.ru",
        hashed_password=password_for_user2,
        is_superuser=True,
    )
    session.add_all([user1, user2])
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
