"""add table author

Revision ID: 5e97cd963f96
Revises: 761c0d0f7e96
Create Date: 2025-05-18 13:22:43.068662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e97cd963f96"
down_revision: Union[str, None] = "761c0d0f7e96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("biography", sa.String(), nullable=True),
        sa.Column("date_birth", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authors_full_name"), "authors", ["full_name"], unique=False)
    op.create_index(op.f("ix_authors_id"), "authors", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_authors_id"), table_name="authors")
    op.drop_index(op.f("ix_authors_full_name"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
