"""add table library

Revision ID: e8bc0666bfb9
Revises: 9295e78c9875
Create Date: 2025-05-18 13:38:01.950382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8bc0666bfb9"
down_revision: Union[str, None] = "9295e78c9875"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "borrowedbookss",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("reader_id", sa.Integer(), nullable=False),
        sa.Column("borrow_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("return_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reader_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reader_id", "book_id", name="idx_unique_reader_book"),
    )
    op.create_index(op.f("ix_borrowedbookss_id"), "borrowedbookss", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_borrowedbookss_id"), table_name="borrowedbookss")
    op.drop_table("borrowedbookss")
    # ### end Alembic commands ###
